# Configuration for scheduled job sources
sources:
  - name: ai_news
    prompt: "Summarize the latest AI news from this RSS feed, process it and capture it in the knowledge graph."
    source_type: RSS
    url: "https://news.smol.ai/rss.xml"

  - name: thought_leaders
    prompt: "Capture ideas from thought leaders in the knowledge graph. If you don't find anything new and worthwhile, just say 'No new ideas found'."
    source_type: X
    handles:
      - EMostaque
      - elonmusk
      - EpochAIResearch
      - DavidSacks
      - BasedBeffJezos

  - name: openai_announcements
    prompt: "List the latest product launches, research, ideas, new capabilities and milestones by OpenAI Capture these in the knowledge graph. If you don't find anything new and worthwhile, just say 'No new ideas found'."
    source_type: X
    handles:
      - OpenAI
      - OpenAINewsroom
      - OpenAIDevs
      - ChatGPTapp
      - sama
      - gdb

  - name: energy_news
    prompt: "List the latest development, research, new capabilities and milestones in energy production, smart grid, energy storage, battery technology. Capture these in the knowledge graph."
    source_type: X
    handles:
      - BESTmag_news
      - EnergyStorageN
      - REWorld
      - PVTech
      - BatteryPowerMag
      - GreentechMedia
      - AltEnergyMag

  - name: crypto_news
    prompt: "List the latest development, research, new capabilities and milestones in crypto, blockchain, web3, decentralized finance. Capture these in the knowledge graph."
    source_type: X
    handles:
      - CoinMarketCap
      - CoinDesk
      - CoinTelegraph
      - worldcoin

  - name: synbio_news
    prompt: "List the latest development, research, new capabilities and milestones in synthetic biology, gene sequencing, gene editing, alternative proteins, longevity, digital health. Capture these in the knowledge graph. If you don't find anything new and worthwhile, just say 'No new ideas found'."
    source_type: X
    handles:
      - nextmedhealth
      - GoodFoodInst
      - davidasinclair
      - colossal
      
      
      
      
      
    